"""SOME/IP 模糊测试工具的核心引擎层（无 GUI 依赖）。"""

from someip_fuzzer.core.mutator import (
    HEADER_LEN,
    MUTATOR_REGISTRY,
    BaseMutator,
    MutationResult,
    MutationScheduler,
    OFFSET_CLIENT_ID,
    OFFSET_IFACE_VER,
    OFFSET_LENGTH,
    OFFSET_METHOD_ID,
    OFFSET_MSG_TYPE,
    OFFSET_PROTO_VER,
    OFFSET_RETURN_CODE,
    OFFSET_SERVICE_ID,
    OFFSET_SESSION_ID,
    get_mutator,
    list_mutators,
    register_mutator,
    replace_header_byte,
    replace_header_bytes,
    replace_length_field,
)

__all__ = [
    "HEADER_LEN",
    "MUTATOR_REGISTRY",
    "BaseMutator",
    "MutationResult",
    "MutationScheduler",
    "OFFSET_CLIENT_ID",
    "OFFSET_IFACE_VER",
    "OFFSET_LENGTH",
    "OFFSET_METHOD_ID",
    "OFFSET_MSG_TYPE",
    "OFFSET_PROTO_VER",
    "OFFSET_RETURN_CODE",
    "OFFSET_SERVICE_ID",
    "OFFSET_SESSION_ID",
    "get_mutator",
    "list_mutators",
    "register_mutator",
    "replace_header_byte",
    "replace_header_bytes",
    "replace_length_field",
]
